# Generated by Django 4.0.3 on 2023-06-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_gender_user_language_level_user_native_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(default='english', max_length=50),
        ),
    ]
