# Generated by Django 4.0.3 on 2023-07-10 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_user_native_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='display_language',
            field=models.CharField(default='eng', max_length=3),
        ),
    ]
