# Generated by Django 4.0.3 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_user_display_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='display_language',
            field=models.CharField(default='en', max_length=3),
        ),
    ]
