# Generated by Django 4.0.3 on 2023-07-18 11:06

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_display_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../recordings/puffin.jpg', upload_to=account.models.user_directoryphotos),
        ),
    ]
