# Generated by Django 4.0.3 on 2023-07-21 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_birthday_user_birthyear'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('N', 'NotIdentified')], default='N', max_length=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='native_language',
            field=models.CharField(default='English', max_length=50),
        ),
    ]
