# Generated by Django 4.0.3 on 2023-08-12 18:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_alter_user_native_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birthyear',
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
