# Generated by Django 4.0.3 on 2024-03-07 15:30

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_usersession'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_photo',
            field=models.ImageField(blank=True, default='../recordings/user/profile_photos/profile.jpg', upload_to=account.models.user_directoryphotos),
        ),
    ]
