# Generated by Django 4.0.3 on 2022-08-15 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lesson',
            options={},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={},
        ),
        migrations.AlterModelOptions(
            name='userpromptscore',
            options={},
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
