# Generated by Django 4.0.3 on 2023-07-18 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertaskscorestats',
            old_name='number_tentative',
            new_name='number_tries',
        ),
    ]
