# Generated by Django 4.0.3 on 2022-04-11 09:59

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0002_topic_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=254)),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.AddField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='user',
            name='progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), default=[0], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='spoken_languages',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=255), default=[''], max_length=25, size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer.', max_length=150, unique=True, verbose_name='username'),
        ),
        migrations.CreateModel(
            name='Prompt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=25, unique=True)),
                ('text', models.CharField(max_length=500, verbose_name='prompt text')),
                ('audio_url', models.CharField(blank=True, max_length=100, verbose_name='audio url')),
                ('Lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captini.lesson')),
            ],
        ),
        migrations.AddField(
            model_name='lesson',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='captini.topic'),
        ),
        migrations.CreateModel(
            name='Flashcard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_id', models.CharField(max_length=25, unique=True)),
                ('Prompt', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='captini.prompt')),
            ],
        ),
    ]
