# Generated by Django 4.0.3 on 2022-08-26 13:04

import captini.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captini', '0002_alter_lesson_options_alter_prompt_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_description',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100),
        ),
        migrations.CreateModel(
            name='UserTaskRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording', models.BinaryField()),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_recording', to='captini.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_recording', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
