# Generated by Django 4.0.3 on 2024-03-07 15:34

import captini.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0002_rename_number_tentative_usertaskscorestats_number_tries'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usertaskrecording',
            name='unique_user_task_stats',
        ),
        migrations.AddField(
            model_name='usertaskrecording',
            name='recording',
            field=models.FileField(default='file_example', upload_to=captini.models.directory_path),
        ),
    ]
