# Generated by Django 4.0.3 on 2024-03-07 15:38

import captini.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0003_remove_usertaskrecording_unique_user_task_stats_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, default='../lessons_images/lessons/default.jpeg', upload_to=captini.models.lessons_photos),
        ),
    ]
