# Generated by Django 4.0.3 on 2022-04-11 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0003_lesson_remove_user_age_topic_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flashcard',
            name='text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='flashcard text'),
        ),
        
    ]
