# Generated by Django 4.0.3 on 2022-08-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0004_alter_prompt_flashcard_text_alter_task_audio_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskrecording',
            name='recording',
            field=models.FileField(upload_to='recordings/'),
        ),
    ]
