# Generated by Django 4.0.3 on 2024-03-07 15:57

import captini.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0004_lesson_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, default='../recordings/topics/default.jpeg', upload_to=captini.models.topics_photos),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='photo',
            field=models.ImageField(blank=True, default='../recordings/lessons/default.jpeg', upload_to=captini.models.lessons_photos),
        ),
    ]
