# Generated by Django 4.0.3 on 2024-03-07 16:11

import captini.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0005_topic_photo_alter_lesson_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='photo',
            field=models.ImageField(blank=True, default='../recordings/topics/default_topic.jpeg', upload_to=captini.models.topics_photos),
        ),
    ]
