# Generated by Django 4.0.3 on 2022-08-29 11:36

import captini.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0005_alter_usertaskrecording_recording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertaskrecording',
            name='recording',
            field=models.FileField(upload_to=captini.models.user_directory_path),
        ),
    ]
