# Generated by Django 4.0.3 on 2022-11-01 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0006_alter_usertaskrecording_recording'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prompt',
            old_name='Lesson',
            new_name='lesson',
        ),
    ]
