# Generated by Django 4.0.3 on 2022-04-25 12:29

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0006_alter_flashcard_prompt_alter_prompt_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='level',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='progress',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(blank=True), blank=True, size=None),
        ),
    ]
