# Generated by Django 4.0.3 on 2022-04-26 06:53

import captini.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0007_topic_level_alter_user_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=captini.models.TopicNameField(default='', max_length=100),
        ),
    ]
