# Generated by Django 4.0.3 on 2022-04-26 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0008_alter_topic_topic_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flashcard',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='prompt',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'ordering': ['id']},
        ),
    ]
