# Generated by Django 4.0.3 on 2023-05-08 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0008_rename_level_topic_number_remove_task_prompt_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='topic_name',
            field=models.CharField(max_length=100),
        ),
    ]
