# Generated by Django 4.0.3 on 2023-06-16 13:47

import captini.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captini', '0009_alter_topic_topic_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='audio_url',
        ),
        migrations.CreateModel(
            name='ExampleTaskRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=6)),
                ('recording', models.FileField(upload_to=captini.models.example_recording_directory_path)),
                ('time_created', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_example', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
