# Generated by Django 4.0.3 on 2022-05-05 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0010_user_country_rank_user_global_rank_user_score'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='Prompt',
            new_name='prompt',
        ),
        migrations.RenameField(
            model_name='prompt',
            old_name='display_id',
            new_name='prompt_identifier',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='audio_url',
        ),
        migrations.RemoveField(
            model_name='prompt',
            name='text',
        ),
        migrations.AddField(
            model_name='prompt',
            name='prompt_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='prompt description'),
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt_identifier', models.CharField(max_length=25, unique=True)),
                ('task_text', models.TextField(max_length=255, verbose_name='task text')),
                ('audio_url', models.CharField(blank=True, max_length=500, verbose_name='audio url')),
                ('prompt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='captini.prompt')),
            ],
        ),
    ]
