# Generated by Django 4.0.3 on 2023-06-16 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0010_remove_task_audio_url_exampletaskrecording'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletaskrecording',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_example', to='captini.task'),
        ),
    ]
