# Generated by Django 4.0.3 on 2023-06-23 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0011_alter_exampletaskrecording_task'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='usertaskrecording',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task'),
        ),
    ]
