# Generated by Django 4.0.3 on 2022-05-05 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0011_rename_prompt_flashcard_prompt_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='prompt_identifier',
            field=models.CharField(max_length=25),
        ),
    ]
