# Generated by Django 4.0.3 on 2023-06-23 15:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captini', '0012_usertaskrecording_unique_user_task'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id_score', to='captini.task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_score', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
