# Generated by Django 4.0.3 on 2022-05-05 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0012_alter_task_prompt_identifier'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flashcard',
            old_name='display_id',
            new_name='prompt_identifier',
        ),
    ]
