# Generated by Django 4.0.3 on 2023-06-26 14:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('captini', '0013_usertaskscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTaskScoreStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_mean', models.IntegerField(default=0)),
                ('number_tentative', models.IntegerField(default=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='usertaskscore',
            name='task',
        ),
        migrations.RemoveField(
            model_name='usertaskscore',
            name='user',
        ),
        migrations.RemoveConstraint(
            model_name='usertaskrecording',
            name='unique_user_task',
        ),
        migrations.AddConstraint(
            model_name='usertaskrecording',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task_stats'),
        ),
        migrations.DeleteModel(
            name='UserTaskScore',
        ),
        migrations.AddField(
            model_name='usertaskscorestats',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id_score', to='captini.task'),
        ),
        migrations.AddField(
            model_name='usertaskscorestats',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_task_score', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usertaskscorestats',
            constraint=models.UniqueConstraint(fields=('user', 'task'), name='unique_user_task'),
        ),
    ]
