# Generated by Django 4.0.3 on 2022-05-31 09:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0013_rename_display_id_flashcard_prompt_identifier'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPromptScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_topic', models.CharField(max_length=255)),
                ('prompt_identifier', models.CharField(max_length=25, unique=True)),
                ('score', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
