# Generated by Django 4.0.3 on 2022-05-31 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0014_userpromptscore'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpromptscore',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_prompt_score', to=settings.AUTH_USER_MODEL),
        ),
    ]
