# Generated by Django 4.0.3 on 2023-06-26 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0014_usertaskscorestats_remove_usertaskscore_task_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usertaskrecording',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
