# Generated by Django 4.0.3 on 2022-05-31 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0015_alter_userpromptscore_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='location',
        ),
    ]
