# Generated by Django 4.0.3 on 2023-07-10 06:38

import captini.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0015_usertaskrecording_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exampletaskrecording',
            name='recording',
            field=models.FileField(max_length=150, upload_to=captini.models.example_recording_directory_path),
        ),
    ]
