# Generated by Django 4.0.3 on 2022-06-01 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0016_remove_user_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpromptscore',
            options={'ordering': ['prompt_identifier']},
        ),
        migrations.AddField(
            model_name='prompt',
            name='flashcard_text',
            field=models.CharField(blank=True, default='', max_length=500, verbose_name='flashcard text'),
        ),
        migrations.DeleteModel(
            name='Flashcard',
        ),
    ]
