# Generated by Django 4.0.3 on 2022-06-01 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0017_alter_userpromptscore_options_prompt_flashcard_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='topic_description',
            field=models.TextField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(max_length=254),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='flashcard_text',
            field=models.TextField(blank=True, default='', max_length=500, verbose_name='flashcard text'),
        ),
        migrations.AlterField(
            model_name='prompt',
            name='prompt_description',
            field=models.TextField(blank=True, max_length=200, verbose_name='prompt description'),
        ),
        migrations.AlterField(
            model_name='task',
            name='task_text',
            field=models.CharField(max_length=255, verbose_name='task text'),
        ),
    ]
