# Generated by Django 4.0.3 on 2022-06-01 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0018_topic_topic_description_alter_lesson_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prompt',
            name='prompt_description',
        ),
    ]
