# Generated by Django 4.0.3 on 2022-06-03 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0019_remove_prompt_prompt_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='progress',
        ),
    ]
