# Generated by Django 4.0.3 on 2022-06-10 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0020_remove_user_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='prompt_identifier',
        ),
    ]
