# Generated by Django 4.0.3 on 2022-06-20 10:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('captini', '0021_alter_user_managers_alter_user_birthday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birthday',
            field=models.DateField(default=datetime.datetime(2022, 6, 20, 10, 15, 56, 683321)),
        ),
    ]
